# Generated by Django 6.0.4 on 2026-04-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='github_url',
            field=models.URLField(),
        ),
    ]
